from enum import Enum

class EducationLevel(Enum):
    HIGH_SCHOOL_DIPLOMA = "HIGH_SCHOOL_DIPLOMA"
    SOME_COLLEGE = "SOME_COLLEGE"
    ASSOCIATES = "ASSOCIATES"
    BACHELORS = "BACHELORS"
    MASTERS = "MASTERS"
    DOCTORAL = "DOCTORAL"
    PROFESSIONAL = "PROFESSIONAL"

class EmploymentLevel(Enum):
    ENTRY = "ENTRY"
    INTERMEDIATE = "INTERMEDIATE"
    MID = "MID"
    SENIOR = "SENIOR"
    EXECUTIVE = "EXECUTIVE"